# Generated by Django 3.2.6 on 2021-09-06 14:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Proffesional_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=150)),
                ('phone_Number', models.CharField(max_length=150)),
                ('adhaar_Number', models.CharField(max_length=150)),
                ('native_Place', models.CharField(max_length=150)),
                ('date_Of_Birth', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('departments', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('occupation_Location', models.CharField(max_length=150, null=True)),
                ('office_Levels', models.CharField(max_length=150, null=True)),
                ('office_Location', models.CharField(max_length=150, null=True)),
                ('organisation', models.CharField(max_length=150, null=True)),
                ('districts', models.CharField(max_length=150, null=True)),
                ('constituency', models.CharField(max_length=150, null=True)),
                ('mandal', models.CharField(max_length=150, null=True)),
                ('panchayath', models.CharField(max_length=150, null=True)),
                ('village', models.CharField(max_length=150, null=True)),
                ('central_Organisation', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
