# Generated by Django 3.2.6 on 2021-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APCS_Conduct_Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('supporting_files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='APCS_Leave_Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('supporting_files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='APCS_Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('supporting_files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('supporting_files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Convid_Plasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('supporting_files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Employement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('supporting_files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('supporting_files', models.FileField(upload_to='files')),
            ],
        ),
    ]
