# Generated by Django 3.2.6 on 2021-09-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apcs_conduct_rules_apcs_leave_rules_apcs_rules_blood_donor_convid_plasma_employement_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side_bar',
            name='icon_name',
        ),
    ]
