# Generated by Django 3.2.6 on 2021-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_farmer_supporting_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='supporting_files',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
