# Generated by Django 3.2.6 on 2021-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_farmer_supporting_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
