# Generated by Django 3.2.6 on 2021-09-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_farmer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apcs_conduct_rules',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='apcs_conduct_rules',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apcs_leave_rules',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='apcs_leave_rules',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apcs_rules',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='apcs_rules',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blood_donor',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='blood_donor',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='convid_plasma',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='convid_plasma',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employement',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='employement',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='supporting_images',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='school',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='apcs_conduct_rules',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apcs_conduct_rules',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='apcs_leave_rules',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apcs_leave_rules',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='apcs_rules',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apcs_rules',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='blood_donor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blood_donor',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='convid_plasma',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convid_plasma',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='employement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employement',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='supporting_files',
            field=models.FileField(blank=True, default='no file', null=True, upload_to='files'),
        ),
    ]
